force-app/main/default/objects/BatchInfo__c/BatchInfo__c.object-meta.xml
<CustomObject>
    <label>BatchInfo</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>BatchInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BatchInfos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchInfo__c/fields/Businesshour__c.field-meta.xml
<CustomField>
    <fullName>Businesshour__c</fullName>
    <label>Businesshour</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/DataRepresentation__c.field-meta.xml
<CustomField>
    <fullName>DataRepresentation__c</fullName>
    <label>DataRepresentation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/Dates__c.field-meta.xml
<CustomField>
    <fullName>Dates__c</fullName>
    <label>Dates</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/Filter_Name__c.field-meta.xml
<CustomField>
    <fullName>Filter_Name__c</fullName>
    <label>Filter Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/LastRefreshedDate__c.field-meta.xml
<CustomField>
    <fullName>LastRefreshedDate__c</fullName>
    <label>LastRefreshedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/OwnerDataRepresentation__c.field-meta.xml
<CustomField>
    <fullName>OwnerDataRepresentation__c</fullName>
    <label>OwnerDataRepresentation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/SobjectFieldType__c.field-meta.xml
<CustomField>
    <fullName>SobjectFieldType__c</fullName>
    <label>SobjectFieldType</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/SobjectFieldValue__c.field-meta.xml
<CustomField>
    <fullName>SobjectFieldValue__c</fullName>
    <label>SobjectFieldValue</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/SobjectRecordType__c.field-meta.xml
<CustomField>
    <fullName>SobjectRecordType__c</fullName>
    <label>SobjectRecordType</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/SobjectType__c.field-meta.xml
<CustomField>
    <fullName>SobjectType__c</fullName>
    <label>SobjectType</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/WillRefresh__c.field-meta.xml
<CustomField>
    <fullName>WillRefresh__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WillRefresh</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/caseComarisionTest.cls
@istest
public class caseComarisionTest
{
    @testsetup
    Public static void averagetimechartcontrollertest1()
    {
        BatchInfo__c btchInfo = new BatchInfo__c();
        btchInfo.Businesshour__c = 'India';
        btchInfo.Dates__c = 'Last 6 Months';
        btchInfo.Filter_Name__c = 'test';
        btchInfo.WillRefresh__c = True;
        btchInfo.SobjectFieldValue__c = 'InProgress';
        btchInfo.SobjectRecordType__c = 'Internal';
        btchInfo.OwnerDataRepresentation__c = '{"0052w000003cdO7AAI:InProgress":3.53}';
        insert btchInfo;
        
        Attachment att = new Attachment();
        att.ParentId = btchInfo.Id;
        att.Body = Blob.valueof('{"a0EBh0000003YjqMAE:Assess:1":8393.32,"a0EBh0000003YjqMAE:New:1":6.92}');
        att.Name = 'test';
        system.debug('att>>>'+att);
        insert att;
        
        Attachment at = new Attachment();
        at.ParentId = btchInfo.Id;
        at.Body = Blob.valueof('{"a0EBh0000003YjqMAE:Assess:1":8393.32,"a0EBh0000003YjqMAE:New:1":6.92}');
        at.Name = 'test';
        system.debug('at>>>'+at);
        insert at;
        System.assert(1==1,'List should not be empty');
    }
    
    @istest
    Public static void caseComarisionTest1()
    {
            BatchInfo__c btchInfo = new BatchInfo__c();
            btchInfo.Businesshour__c = 'India';
            btchInfo.Dates__c = 'this week';
            btchInfo.SobjectFieldType__c = 'Status';
            btchInfo.WillRefresh__c = True;
            btchInfo.LastRefreshedDate__c = system.today();
            btchInfo.SobjectFieldValue__c = 'New';
            btchInfo.SobjectRecordType__c = 'Internal';
            btchInfo.SobjectType__c='Case';
            btchInfo.OwnerDataRepresentation__c = '{"0052w000003cdO7AAI:InProgress":3.53}';
            btchInfo.dataRepresentation__c = '{"0052w000003cdO7AAI:InProgress":3.53}';
            
            insert btchInfo;
            system.debug('btchInfo'+btchInfo);
            
            BatchInfo__c bchInfo = new BatchInfo__c();
            bchInfo.Businesshour__c = 'India';
            bchInfo.Dates__c = 'this week';
            bchInfo.SobjectFieldType__c = 'Status';
            bchInfo.WillRefresh__c = True;
            bchInfo.SobjectFieldValue__c = 'New';
            bchInfo.SobjectRecordType__c = 'Internal';
            bchInfo.SobjectType__c='Case';
            bchInfo.OwnerDataRepresentation__c = '{"0052w000003cdO7AAI:InProgress":3.53}';
            bchInfo.dataRepresentation__c = '{"0052w000003cdO7AAI:InProgress":3.53}';
            bchInfo.Filter_Name__c='test';
            insert bchInfo;
          Profile pf= [Select Id from profile where Name='System Administrator']; 
        
       /* String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+RandomId; 
            
         User uu=new User(firstname = 'ABC', 
                         lastName = 'XYZ', 
                         email = uniqueName + '@test' + orgId + '.org', 
                         Username = uniqueName + '@test' + orgId + '.org', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = uniqueName.substring(18, 23), 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US', 
                         ProfileId = pf.Id
                        ); 
        
        
             insert uu;*/
        
             string username=UserInfo.getName();
            CaseComparison.getAllCasesForUser(username, bchInfo.Filter_Name__c, 'New,Research,Solution');
        
        
        list<case> cd= new list<case>();
        for(integer i=0;i<50;i++)
        {
            case cs= new case();
            cs.status='New';
            cs.Priority='Email';
            cs.ownerid='0052w000003dXf7AAE';
            cd.add(cs);
        }
        for(integer i=0;i<50;i++)
        {
            case cs= new case();
            cs.status='New';
            cs.Priority='Email';
            cs.ownerid='0052w000003cdO7AAI';
            cd.add(cs);
        }
        insert cd;
        CaseComparison.getAllUser();
    }
    
}